import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ToastContainer } from "react-toastify";
import "./globals.css";
import { UIContextProvider } from "./providers/ui.provider";
config.autoAddCss = false;

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Referral Builder App",
  description: "Generated by create next app",
};

export const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <UIContextProvider>
          <div className="flex flex-col min-h-screen">
            <main className="flex-grow">
              <div className="max-w-7xl mx-auto bg-white w-full p-4">
                {children}
                <ToastContainer
                  position="top-right"
                  autoClose={5000}
                  hideProgressBar={false}
                  newestOnTop={false}
                  closeOnClick={false}
                  rtl={false}
                  pauseOnFocusLoss
                  draggable
                  pauseOnHover
                  theme="light"
                />
              </div>
            </main>

            <footer className="bg-gray-800 text-white w-full h-[100px] py-4">
              <div className="max-w-7xl mx-auto px-4">
                <p className="text-center">
                  © 2025 Your Company. All rights reserved.
                </p>
              </div>
            </footer>
          </div>
        </UIContextProvider>
      </body>
    </html>
  );
}

export default RootLayout